### ISSUE TITLE
Bug: "Error opening some documents" when a filename contains ~ or is a temp docx file

### ISSUE THREAD

**Issue by 4abhinavjain** [rimoun-g/Autoit_WdReplacer-Autoit#1]
Great tool, I noticed that it throws the following error when there are files with "~" in the beginning. 
![image](https://user-images.githubusercontent.com/34500467/232723022-7308bae3-924d-43a7-b3ea-b1a517382d0d.png)

Those are generally temp files with no readable content so it is likely that the error is just because the script could not handle it properly.

**Comment by rimoun-g** [comment]
Yea, the script should be amended to exclude the temporary files that include this sign of "~$".
